### ISSUE TITLE
And if i don't want any prefix ??

### ISSUE THREAD

**Issue by Tocard** [basgys/goxml2json#13]
`func (dec *Decoder) Decode(root *Node) error {

	if dec.contentPrefix == "" {
		dec.contentPrefix = contentPrefix
	}
	if dec.attributePrefix == "" {
		dec.attributePrefix = attrPrefix
	}
`

**Comment by basgys** [comment]
As I explained in this [PR](https://github.com/basgys/goxml2json/pull/12), there can be clashes if a content prefix and an attribute prefix have the same name. 

So if we allow to remove prefixes, we should either return an error when it occurs or quietly fail.
