### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by yudao** [basgys/goxml2json#14]
Hi!,

I've seen this interesting [PR](https://github.com/basgys/goxml2json/commit/27ab359192c4f7d1a18521e2a40dcf21b39291eb).

Could you create a new version of the last corrections? I'm using glide and want to keep semver packages.

Or tell us if the project is abandoned to find other solutions or create a new forked one.

Thanks a lot for your work!

Yu.

**Comment by basgys** [comment]
Hi @yudao!

I created the `v1.1.0` tag. Sorry for the delay.

Don't forget to migrate from glide to [dep](https://github.com/golang/dep). :)

**Comment by yudao** [comment]
@basgys No problemo! Thanks a lot for your update. dep is on my todolist ;)
