### ISSUE TITLE
Converting xml to wrong json

### ISSUE THREAD

**Issue by iN3O** [basgys/goxml2json#3]
I used xj.Convert() to convert the following xml file(in sample.tar.gz) to json file . When I tried to unmarshal the same json file using "encoding/json", its giving me error "invalid character '\n' in string literal".

[sample.tar.gz](https://github.com/basgys/goxml2json/files/321727/sample.tar.gz)

**Comment by basgys** [comment]
Fixed in commit https://github.com/basgys/goxml2json/commit/37755807df1e00a71290838dee6531bdc26e92f4
