### ISSUE TITLE
Conversion do not happen if xml encoding is "ISO-8859-1"

### ISSUE THREAD

**Issue by Anmol-Porwal18** [basgys/goxml2json#9]
Works when encoding is "UTF-8"

**Comment by basgys** [comment]
Can you provide test data?

**Comment by Anmol-Porwal18** [comment]
Sure,

`<?xml version="1.0" encoding="ISO-8859-1"?><hello>world</hello>`

gives an empty string after conversion

**Comment by basgys** [comment]
Can you provide an XML in a file encoded in `ISO-8859-1`? Preferably with special characters.

The XML you provided me is useless. When it comes to charset issues, it is always better to have the exact same bytes to reproduce an error :)

**Comment by basgys** [comment]
@Anmol-Porwal18 Please take a look at this https://github.com/basgys/goxml2json/pull/10. I still need your file to validate the PR. Cheers

**Comment by Anmol-Porwal18** [comment]
@basgys I don't have an xml with special characters but this is what I get from web:


[xml.xml.zip](https://github.com/basgys/goxml2json/files/636182/xml.xml.zip)

**Comment by basgys** [comment]
@Anmol-Porwal18 Ok, then I'd suggest to give it a whirl with your app and see if it works with the PR I've just opened.

**Comment by Anmol-Porwal18** [comment]
Sure, I'll try it and let you know
